coverage:
  range: 60..80

flag_management:
  # the rules that will be followed for any flag added, generally
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 10%
      - type: patch
        target: auto
