coverage:
  status:
    project:
      # default is the status check's name, not default settings
      default:
        paths:
          - lib

flag_management:
  # the rules that will be followed for any flag added, generally
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 10%
      - type: patch
        target: auto
